### ISSUE TITLE
Documentation export variables vol2bird incorrect?

### ISSUE THREAD

**Issue by BerendWijers** [adokter/vol2bird#110]
Hi,

I've compiled vol2bird now sucesfully and I've ran into the problem that my vol2bird lib could not be found. The documentation for Ubuntu 14 stated:

```
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${RADAR_ROOT_DIR}/opt/hlhdf/lib:${RADAR_ROOT_DIR}/opt/rave/lib:${RADAR_ROOT_DIR}/opt/rsl/lib:${RADAR_ROOT_DIR}/opt/radar/vol2bird/lib
export PATH=${PATH}:${RADAR_ROOT_DIR}/opt/vol2bird/bin
```
However, in my run through of compiling everything my paths were different, most notably:
```${RADAR_ROOT_DIR}/opt/**radar**/vol2bird/lib```
I've changed to:
```${RADAR_ROOT_DIR}/opt/vol2bird/lib```

which works.

**Comment by adokter** [comment]
Thannks, corrected by commit 7365c58232cd97ab0c504a6b1fb8906a06ee3147
