### ISSUE TITLE
failed to load configuration file

### ISSUE THREAD

**Issue by ohueppop** [adokter/vol2bird#147]
Two errors occurred while reading the user configuration file 'options.conf':

options.conf:108: invalid boolean value for option 'USE_MISTNET' (needs to be FALSE instead of 0)
options.conf:119: missing equal sign after option 'MISTNET_PATH'

(Docker version 19.03.12, Ubuntu 18.04)

**Comment by adokter** [comment]
Thanks Ommo, fixed in https://github.com/adokter/vol2bird/commit/16634c2813d8a654bb942b11c4ff3f695db191a9
