### ISSUE TITLE
How to use its API in python?

### ISSUE THREAD

**Issue by GStarmin** [adokter/vol2bird#194]
when I use the Makefile in pyvol2bird, I get the following error:

pyvol2bird.c:27:10: fatal error: Python.h: No such file or directory
   27 | #include "Python.h"
      |          ^~~~~~~~~~
compilation terminated.
cp: cannot stat '.dep/pyvol2bird.d': No such file or directory
/bin/sh: 3: cannot open .dep/pyvol2bird.d: No such file
cc -c -I../lib -I.   -I/usr/include pyvol2bird.c -o pyvol2bird.o
pyvol2bird.c:27:10: fatal error: Python.h: No such file or directory
   27 | #include "Python.h"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:97: pyvol2bird.o] Error 1

**Comment by adokter** [comment]
Hi @GStarmin, the python api is very rudimentary and hasn't been fully developed, contribution would be welcome. For now I suggest using vol2bird as a standalone program (see https://github.com/adokter/vol2birdinstall for the installer), or through the R packages vol2birdR and bioRad (https://github.com/adokter/vol2birdR, https://github.com/adokter/bioRad).
