### ISSUE TITLE
Missing /how elements

### ISSUE THREAD

**Issue by peterdesmet** [adokter/vol2bird#56]
In https://github.com/adokter/vol2bird/wiki/ODIM-bird-profile-format-specification I noticed:

* `/how/clutterMap` is listed twice
* `wavelength` is missing (we find it in the [example file](https://github.com/enram/infrastructure/blob/master/hdf5_handling/profile_example.h5))
* `task_version` is missing (we find it in the [example file](https://github.com/enram/infrastructure/blob/master/hdf5_handling/profile_example.h5))

I have apparently the rights to edit the wiki right away, but I wanted to check.

**Comment by adokter** [comment]
Thanks, I corrected it
